export interface MedicineInfo {
  name: string;
  category: string;
  dosageForm: string;
  strength: string;
  manufacturer: string;
  indication: string;
  classification: string;
}

export const MEDICINES: MedicineInfo[] = [
  { name: 'Acetocillin',   category: 'Antidiabetic',   dosageForm: 'Cream',      strength: '938 mg', manufacturer: 'Roche Holding AG',                        indication: 'Virus',      classification: 'Over-the-Counter' },
  { name: 'Acetomet',      category: 'Antiviral',       dosageForm: 'Drops',      strength: '226 mg', manufacturer: 'GlaxoSmithKline plc',                      indication: 'Pain',       classification: 'Prescription' },
  { name: 'Acetomycin',    category: 'Analgesic',       dosageForm: 'Inhaler',    strength: '838 mg', manufacturer: 'Novo Nordisk A/S',                         indication: 'Wound',      classification: 'Prescription' },
  { name: 'Acetonazole',   category: 'Antipyretic',     dosageForm: 'Ointment',   strength: '575 mg', manufacturer: 'Bayer AG',                                 indication: 'Wound',      classification: 'Prescription' },
  { name: 'Acetophen',     category: 'Analgesic',       dosageForm: 'Cream',      strength: '76 mg',  manufacturer: 'Merck & Co., Inc.',                        indication: 'Virus',      classification: 'Over-the-Counter' },
  { name: 'Acetoprofen',   category: 'Antibiotic',      dosageForm: 'Inhaler',    strength: '909 mg', manufacturer: 'CSL Limited',                              indication: 'Fever',      classification: 'Prescription' },
  { name: 'Acetostatin',   category: 'Analgesic',       dosageForm: 'Inhaler',    strength: '490 mg', manufacturer: 'CSL Limited',                              indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Acetovir',      category: 'Antidepressant',  dosageForm: 'Injection',  strength: '188 mg', manufacturer: 'Gilead Sciences, Inc.',                    indication: 'Wound',      classification: 'Prescription' },
  { name: 'Amoxicillin',   category: 'Antifungal',      dosageForm: 'Tablet',     strength: '802 mg', manufacturer: 'Teva Pharmaceutical Industries Ltd.',      indication: 'Wound',      classification: 'Over-the-Counter' },
  { name: 'Amoximet',      category: 'Analgesic',       dosageForm: 'Ointment',   strength: '795 mg', manufacturer: 'Gilead Sciences, Inc.',                    indication: 'Pain',       classification: 'Prescription' },
  { name: 'Amoximycin',    category: 'Antipyretic',     dosageForm: 'Syrup',      strength: '808 mg', manufacturer: 'Roche Holding AG',                         indication: 'Fungus',     classification: 'Over-the-Counter' },
  { name: 'Amoxinazole',   category: 'Analgesic',       dosageForm: 'Ointment',   strength: '35 mg',  manufacturer: 'Pfizer Inc.',                              indication: 'Depression', classification: 'Prescription' },
  { name: 'Amoxiphen',     category: 'Antipyretic',     dosageForm: 'Injection',  strength: '984 mg', manufacturer: 'Merck & Co., Inc.',                        indication: 'Pain',       classification: 'Prescription' },
  { name: 'Amoxiprofen',   category: 'Antiviral',       dosageForm: 'Ointment',   strength: '861 mg', manufacturer: 'Novo Nordisk A/S',                         indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Amoxistatin',   category: 'Antiviral',       dosageForm: 'Inhaler',    strength: '46 mg',  manufacturer: 'Sanofi S.A.',                              indication: 'Fever',      classification: 'Over-the-Counter' },
  { name: 'Amoxivir',      category: 'Antifungal',      dosageForm: 'Syrup',      strength: '289 mg', manufacturer: 'Novartis AG',                              indication: 'Virus',      classification: 'Over-the-Counter' },
  { name: 'Cefcillin',     category: 'Antipyretic',     dosageForm: 'Tablet',     strength: '954 mg', manufacturer: 'Takeda Pharmaceutical Company Limited',     indication: 'Fungus',     classification: 'Over-the-Counter' },
  { name: 'Cefmet',        category: 'Antifungal',      dosageForm: 'Tablet',     strength: '440 mg', manufacturer: 'AstraZeneca plc',                          indication: 'Depression', classification: 'Prescription' },
  { name: 'Cefmycin',      category: 'Antifungal',      dosageForm: 'Ointment',   strength: '778 mg', manufacturer: 'Sanofi S.A.',                              indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Cefnazole',     category: 'Antiviral',       dosageForm: 'Inhaler',    strength: '520 mg', manufacturer: 'CSL Limited',                              indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Cefphen',       category: 'Antifungal',      dosageForm: 'Cream',      strength: '991 mg', manufacturer: 'Bristol-Myers Squibb Company',             indication: 'Fungus',     classification: 'Prescription' },
  { name: 'Cefprofen',     category: 'Antiseptic',      dosageForm: 'Tablet',     strength: '245 mg', manufacturer: 'Novartis AG',                              indication: 'Pain',       classification: 'Over-the-Counter' },
  { name: 'Cefstatin',     category: 'Antipyretic',     dosageForm: 'Ointment',   strength: '19 mg',  manufacturer: 'Roche Holding AG',                         indication: 'Fever',      classification: 'Prescription' },
  { name: 'Cefvir',        category: 'Analgesic',       dosageForm: 'Capsule',    strength: '305 mg', manufacturer: 'Bristol-Myers Squibb Company',             indication: 'Wound',      classification: 'Prescription' },
  { name: 'Claricillin',   category: 'Antidiabetic',    dosageForm: 'Tablet',     strength: '734 mg', manufacturer: 'Novo Nordisk A/S',                         indication: 'Virus',      classification: 'Prescription' },
  { name: 'Clarimet',      category: 'Antidepressant',  dosageForm: 'Injection',  strength: '424 mg', manufacturer: 'AstraZeneca plc',                          indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Clarimycin',    category: 'Antibiotic',      dosageForm: 'Syrup',      strength: '254 mg', manufacturer: 'Biogen Inc.',                              indication: 'Pain',       classification: 'Over-the-Counter' },
  { name: 'Clarinazole',   category: 'Antifungal',      dosageForm: 'Syrup',      strength: '362 mg', manufacturer: 'AbbVie Inc.',                              indication: 'Pain',       classification: 'Prescription' },
  { name: 'Clariphen',     category: 'Antidiabetic',    dosageForm: 'Syrup',      strength: '300 mg', manufacturer: 'GlaxoSmithKline plc',                      indication: 'Fungus',     classification: 'Over-the-Counter' },
  { name: 'Clariprofen',   category: 'Antifungal',      dosageForm: 'Tablet',     strength: '123 mg', manufacturer: 'Pfizer Inc.',                              indication: 'Infection',  classification: 'Prescription' },
  { name: 'Claristatin',   category: 'Antipyretic',     dosageForm: 'Capsule',    strength: '47 mg',  manufacturer: 'Pfizer Inc.',                              indication: 'Infection',  classification: 'Prescription' },
  { name: 'Clarivir',      category: 'Analgesic',       dosageForm: 'Tablet',     strength: '14 mg',  manufacturer: 'Bristol-Myers Squibb Company',             indication: 'Pain',       classification: 'Prescription' },
  { name: 'Dextrocillin',  category: 'Antidiabetic',    dosageForm: 'Inhaler',    strength: '392 mg', manufacturer: 'Sanofi S.A.',                              indication: 'Pain',       classification: 'Over-the-Counter' },
  { name: 'Dextromet',     category: 'Antiviral',       dosageForm: 'Syrup',      strength: '564 mg', manufacturer: 'AstraZeneca plc',                          indication: 'Fever',      classification: 'Prescription' },
  { name: 'Dextromycin',   category: 'Antipyretic',     dosageForm: 'Capsule',    strength: '986 mg', manufacturer: 'Takeda Pharmaceutical Company Limited',     indication: 'Wound',      classification: 'Over-the-Counter' },
  { name: 'Dextronazole',  category: 'Antiseptic',      dosageForm: 'Tablet',     strength: '367 mg', manufacturer: 'Boehringer Ingelheim GmbH',                indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Dextrophen',    category: 'Antibiotic',      dosageForm: 'Ointment',   strength: '333 mg', manufacturer: 'Johnson & Johnson',                        indication: 'Wound',      classification: 'Prescription' },
  { name: 'Dextroprofen',  category: 'Antidepressant',  dosageForm: 'Drops',      strength: '389 mg', manufacturer: 'Merck & Co., Inc.',                        indication: 'Diabetes',   classification: 'Over-the-Counter' },
  { name: 'Dextrostatin',  category: 'Antifungal',      dosageForm: 'Capsule',    strength: '296 mg', manufacturer: 'Merck & Co., Inc.',                        indication: 'Wound',      classification: 'Prescription' },
  { name: 'Dextrovir',     category: 'Antifungal',      dosageForm: 'Inhaler',    strength: '940 mg', manufacturer: 'Biogen Inc.',                              indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Dolocillin',    category: 'Antiviral',       dosageForm: 'Ointment',   strength: '451 mg', manufacturer: 'Novo Nordisk A/S',                         indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Dolomet',       category: 'Antifungal',      dosageForm: 'Drops',      strength: '335 mg', manufacturer: 'Amgen Inc.',                               indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Dolomycin',     category: 'Antidiabetic',    dosageForm: 'Capsule',    strength: '135 mg', manufacturer: 'Bayer AG',                                 indication: 'Fungus',     classification: 'Prescription' },
  { name: 'Dolonazole',    category: 'Antifungal',      dosageForm: 'Ointment',   strength: '533 mg', manufacturer: 'GlaxoSmithKline plc',                      indication: 'Pain',       classification: 'Over-the-Counter' },
  { name: 'Dolophen',      category: 'Antibiotic',      dosageForm: 'Capsule',    strength: '469 mg', manufacturer: 'Johnson & Johnson',                        indication: 'Depression', classification: 'Prescription' },
  { name: 'Doloprofen',    category: 'Antibiotic',      dosageForm: 'Inhaler',    strength: '981 mg', manufacturer: 'Eli Lilly and Company',                    indication: 'Fungus',     classification: 'Over-the-Counter' },
  { name: 'Dolostatin',    category: 'Antiviral',       dosageForm: 'Drops',      strength: '865 mg', manufacturer: 'Teva Pharmaceutical Industries Ltd.',      indication: 'Infection',  classification: 'Over-the-Counter' },
  { name: 'Dolovir',       category: 'Antibiotic',      dosageForm: 'Ointment',   strength: '790 mg', manufacturer: 'Sanofi S.A.',                              indication: 'Infection',  classification: 'Prescription' },
  { name: 'Ibuprocillin',  category: 'Antiviral',       dosageForm: 'Injection',  strength: '337 mg', manufacturer: 'CSL Limited',                              indication: 'Infection',  classification: 'Over-the-Counter' },
  { name: 'Ibupromet',     category: 'Antibiotic',      dosageForm: 'Drops',      strength: '919 mg', manufacturer: 'Biogen Inc.',                              indication: 'Depression', classification: 'Prescription' },
  { name: 'Ibupromycin',   category: 'Antibiotic',      dosageForm: 'Injection',  strength: '140 mg', manufacturer: 'Takeda Pharmaceutical Company Limited',     indication: 'Infection',  classification: 'Prescription' },
  { name: 'Ibupronazole',  category: 'Analgesic',       dosageForm: 'Injection',  strength: '720 mg', manufacturer: 'Novartis AG',                              indication: 'Fungus',     classification: 'Prescription' },
  { name: 'Ibuprophen',    category: 'Antifungal',      dosageForm: 'Ointment',   strength: '967 mg', manufacturer: 'AbbVie Inc.',                              indication: 'Depression', classification: 'Over-the-Counter' },
  { name: 'Ibuproprofen',  category: 'Analgesic',       dosageForm: 'Cream',      strength: '178 mg', manufacturer: 'CSL Limited',                              indication: 'Pain',       classification: 'Over-the-Counter' },
  { name: 'Ibuprostatin',  category: 'Antidiabetic',    dosageForm: 'Drops',      strength: '157 mg', manufacturer: 'Amgen Inc.',                               indication: 'Diabetes',   classification: 'Prescription' },
  { name: 'Ibuprovir',     category: 'Antidepressant',  dosageForm: 'Syrup',      strength: '758 mg', manufacturer: 'Eli Lilly and Company',                    indication: 'Fungus',     classification: 'Over-the-Counter' },
  { name: 'Metocillin',    category: 'Analgesic',       dosageForm: 'Tablet',     strength: '892 mg', manufacturer: 'Eli Lilly and Company',                    indication: 'Pain',       classification: 'Over-the-Counter' },
  { name: 'Metomet',       category: 'Analgesic',       dosageForm: 'Syrup',      strength: '271 mg', manufacturer: 'Bayer AG',                                 indication: 'Fungus',     classification: 'Over-the-Counter' },
  { name: 'Metomycin',     category: 'Antifungal',      dosageForm: 'Capsule',    strength: '718 mg', manufacturer: 'Pfizer Inc.',                              indication: 'Wound',      classification: 'Over-the-Counter' },
  { name: 'Metonazole',    category: 'Analgesic',       dosageForm: 'Cream',      strength: '124 mg', manufacturer: 'Pfizer Inc.',                              indication: 'Fever',      classification: 'Prescription' },
  { name: 'Metophen',      category: 'Antiseptic',      dosageForm: 'Tablet',     strength: '404 mg', manufacturer: 'AstraZeneca plc',                          indication: 'Virus',      classification: 'Prescription' },
  { name: 'Metoprofen',    category: 'Antiseptic',      dosageForm: 'Capsule',    strength: '319 mg', manufacturer: 'Novartis AG',                              indication: 'Wound',      classification: 'Prescription' },
  { name: 'Metostatin',    category: 'Antipyretic',     dosageForm: 'Ointment',   strength: '982 mg', manufacturer: 'CSL Limited',                              indication: 'Pain',       classification: 'Over-the-Counter' },
  { name: 'Metovir',       category: 'Antipyretic',     dosageForm: 'Ointment',   strength: '641 mg', manufacturer: 'Takeda Pharmaceutical Company Limited',     indication: 'Infection',  classification: 'Over-the-Counter' },
];
